version: '3.1'
services:

  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=springsecurity
      - MYSQL_USER=aidenpearce
      - MYSQL_PASSWORD=letmein
    ports:
      - "3306:3306"
#    restart: unless-stopped


  springservice:
    image: property-service
    container_name: spring-security-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
#    restart: unless-stopped
    depends_on:
      - db

    environment:
        - DATABASE_USER=aidenpearce
        - DATABASE_PASSWORD=letmein
        - DATABASE_NAME=springsecurity
        - DATABASE_PORT=3306
